In [10]:
import pandas as pd
import numpy as np

In [11]:
df_COD = pd.read_csv(r'C:\Users\Asani\Python\.vscode\Tugas\Data_COD.csv')
df_FF = pd.read_csv(r'C:\Users\Asani\Python\.vscode\Tugas\Data_FF.csv')
df_PUBG = pd.read_csv(r'C:\Users\Asani\Python\.vscode\Tugas\Data_PUBG.csv')

In [12]:
df_COD

Username       waktu  \
0               Rezky kurnia  2023-06-21   
1              Nana Prasetya  2023-06-21   
2           Geraldo Wowiling  2023-06-21   
3                Liya Triana  2023-06-21   
4     Fendinata Rahman Hakim  2023-06-21   
...                      ...         ...   
4995         Pengguna Google  2019-09-30   
4996         Pengguna Google  2019-09-30   
4997         Pengguna Google  2019-09-30   
4998         Pengguna Google  2019-09-30   
4999         Pengguna Google  2019-09-30   

                                               Komentar  Rating  
0     terlalu sangat banyak update tidak jelas simpa...       1  
1     permainan salah satu game favorit saya game ke...       5  
2     game sudah bagus sesungguh semua bagus kecuali...       3  
3           mencari musuh tolong yang pintar kemampuan        2  
4     pilih tim sesuai skill bawah saya dan lawan se...       1  
...                                                 ...     ...  
4995  bagus ada beberapa masuk contoh damage  kaki k...       4  
4996  good permainan tingkat  lagi senjata lebih ban...       4  
4997  orang bodoh yang asal nilai kecil mereka tidak...       5  
4998  untuk dari permainan garena sendiri sudah bagu...       5  
4999  kontrol kurang nyaman dengan sensitifitas terl...       3  

[5000 rows x 4 columns]

In [13]:
# Menggabungkan ketiga dataset dalam satu list
datasets = [df_COD, df_FF, df_PUBG]

# Proses untuk setiap dataset
for df in datasets:
    df["waktu"] = pd.to_datetime(df["waktu"])
    df["tahun"] = df["waktu"].dt.year
    df["bulan"] = df["waktu"].dt.month

## Mendefinisikan kolom Sentimen

In [14]:
# Menentukan ambang batas untuk mengkategorikan sentimen
threshold_positif = 4
threshold_negatif = 2
threshold_netral = 3

# Menerapkan analisis sentimen berdasarkan skor
df_COD['Sentimen'] = df_COD['Rating'].apply(lambda x: 'Positif' if x >= threshold_positif else 'Negatif' 
                                                                if x <= threshold_negatif else 'Netral')

# Menyimpan hasil analisis sentimen ke dalam data frame
df_COD_rating = df_COD[['bulan', 'Rating', 'Sentimen']]

df_COD_rating

bulan  Rating Sentimen
0         6       1  Negatif
1         6       5  Positif
2         6       3   Netral
3         6       2  Negatif
4         6       1  Negatif
...     ...     ...      ...
4995      9       4  Positif
4996      9       4  Positif
4997      9       5  Positif
4998      9       5  Positif
4999      9       3   Netral

[5000 rows x 3 columns]

## Analisis sentimen berdasarkan rating yang diberikan 

In [15]:
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.metrics import accuracy_score

from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV

## Data set Call of Duty

### Membagi dataset

In [16]:
from sklearn.model_selection import train_test_split

X_COD = df_COD_rating[['bulan', 'Rating']]
y_COD = df_COD_rating.Sentimen

X_train, X_test, y_train, y_test = train_test_split(X_COD, y_COD, test_size=0.2, random_state=42, stratify=y_COD)

X_train.shape, X_test.shape, y_train.shape, y_test.shape


((4000, 2), (1000, 2), (4000,), (1000,))

## Model Random Forres

In [17]:
# Membuat Model
model = RandomForestClassifier(n_estimators=200, random_state=42)
model.fit(X_train, y_train)

# Memuat prediksi dari model
y_RFC_pred = model.predict(X_test)

# Menghitung akurasi model
accuracy = accuracy_score(y_test, y_RFC_pred)
print('Accuracy:', accuracy*100,"%")

Accuracy: 100.0 %


## Model KNN

In [18]:
# membuat model
Model_KNN = KNeighborsClassifier(n_neighbors=3)

#Melatih Model
Model_KNN.fit(X_train, y_train)

# Melakukan Uji pada data test
y_KNN_predict = Model_KNN.predict(X_test)

# Menhitung akurasi model
accuracy_KNN = accuracy_score(y_test, y_KNN_predict)
print('Accuracy:', accuracy_KNN*100, "%")

Accuracy: 100.0 %


## Model SVM

In [19]:
from sklearn.preprocessing import LabelEncoder

# Menggunakan LabelEncoder
le = LabelEncoder()
df_COD= df_COD.copy()
df_COD['Sentimen'] = le.fit_transform(df_COD['Sentimen'])


In [20]:
# membuat model
model_SVM = svm.SVC(kernel='linear')

#Melatih Model
model_SVM.fit(X_train, y_train)

#Memprediksi label untuk test set
y_pred = model_SVM.predict(X_test)

# Menghitung akurasi prediksi
accuracy = accuracy_score(y_test, y_pred)
print("Akurasi:", accuracy*100,'%')

Akurasi: 100.0 %


# Analisis Sentimen berdasarkan Komentar yang diberikan

## 1. Dataset Free Fire

In [21]:
# Menentukan ambang batas untuk mengkategorikan sentimen
threshold_positif = 3
threshold_negatif = 2

# Menerapkan analisis sentimen berdasarkan skor
df_FF['Sentimen'] = df_FF['Rating'].apply(lambda x: 'Positif' if x >= threshold_positif else 'Negatif')

# Menyimpan hasil analisis sentimen ke dalam data frame
df_FF = df_FF[['Komentar', 'Sentimen']]

df_FF

Komentar Sentimen
0     tolong permainan ringan  karena kasihan kami y...  Negatif
1     baca info permainan saja terus padahal sinyal ...  Negatif
2     sudah update sinyal kenapa tidak stabil  tolon...  Negatif
3     update terus semua cacat tidak urus jaringan s...  Positif
4     tidak bisa berguna update terus kita kalau mai...  Negatif
...                                                 ...      ...
4995  tolong perbaiki tentang cacat luar zona  hanya...  Negatif
4996  untuk pihak garena free fire indonesia tolong ...  Positif
4997  jangan terlalu ada banyak alasan masalah pada ...  Positif
4998  saya mau kasih tahu buat garena free fire upda...  Positif
4999  akhir akhir saya sering rasa masalah macthing ...  Positif

[5000 rows x 2 columns]

In [22]:
from imblearn.over_sampling import SMOTE
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score


## 1.1. Random Forres Classifier

In [23]:
# Load data
X = df_FF["Komentar"]
y = df_FF["Sentimen"]

# Membuat objek KFold dengan k=5
kfold_FF = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# Melakukan Stratified K-Fold Cross Validation pada data
for fold, (train_index, test_index) in enumerate(kfold_FF.split(X, y)):
    
    # Subset data pelatihan dan data pengujian
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

In [24]:
    # Menghitung jumlah sentimen negatif dan positif pada subset pelatihan
    neg_count_train = np.sum(y_train == 'Negatif')
    pos_count_train = np.sum(y_train == 'Positif')
    
    # Menghitung jumlah sentimen negatif dan positif pada subset pengujian
    neg_count_test = np.sum(y_test == 'Negatif')
    pos_count_test = np.sum(y_test == 'Positif')
    
    print("Train Set:")
    print("Jumlah sentimen negatif:", neg_count_train)
    print("Jumlah sentimen positif:", pos_count_train)
    print("")
    
    print("Test Set:")
    print("Jumlah sentimen negatif:", neg_count_test)
    print("Jumlah sentimen positif:", pos_count_test)
    print("")

Train Set:
Jumlah sentimen negatif: 2460
Jumlah sentimen positif: 1540

Test Set:
Jumlah sentimen negatif: 614
Jumlah sentimen positif: 386



In [25]:
df_FF['Komentar'] = df_FF['Komentar'].fillna('')

# Konversi data teks ke tipe string
df_FF.loc[:, 'Komentar'] = df_FF['Komentar'].astype(str)

C:\Users\Asani\AppData\Local\Temp\ipykernel_4744\2495799523.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_FF['Komentar'] = df_FF['Komentar'].fillna('')
C:\Users\Asani\AppData\Local\Temp\ipykernel_4744\2495799523.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_FF.loc[:, 'Komentar'] = df_FF['Komentar'].astype(str)


In [26]:
# Membuat objek vectorizer dan mengubah data latih ke dalam representasi vektor
vectorizer = TfidfVectorizer(max_features=1000, binary=True)
X_vect = vectorizer.fit_transform(df_FF['Komentar'].values)

# Mengubah representasi vektor menjadi array numpy
X_array = X_vect.toarray()

In [27]:
# Melakukan oversampling menggunakan SMOTE
sm = SMOTE()
X_resampled, y_resampled = sm.fit_resample(X_array, y)

unique, counts = np.unique(y_resampled, return_counts=True)
print(list(zip(unique, counts)))

[('Negatif', 3074), ('Positif', 3074)]


In [28]:
# Membuat model RandomForestClassifier
model = RandomForestClassifier()

# Melakukan cross validation
scores = cross_val_score(model, X_resampled, y_resampled, cv=kfold_FF)

# Menampilkan hasil kinerja model pada setiap fold
for fold, score in enumerate(scores):
    print("Fold", fold+1, "Accuracy:", score*100,"%")


Fold 1 Accuracy: 81.0569105691057 %
Fold 2 Accuracy: 79.02439024390245 %
Fold 3 Accuracy: 78.04878048780488 %
Fold 4 Accuracy: 78.27502034174125 %
Fold 5 Accuracy: 80.14646053702197 %


In [29]:
# Melatih model dengan data latih yang telah di-resampling
model.fit(X_resampled, y_resampled)

# Menghitung akurasi dan prediksi pada data uji
X_test_vect = vectorizer.transform(X_test)
y_pred = model.predict(X_test_vect)

# Menampilkan hasil evaluasi model
print("Accuracy: {:.2f}%".format(accuracy_score(y_test, y_pred) * 100))
print("F1 Score: {:.2f}".format(f1_score(y_test, y_pred, average='weighted') * 100))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 100.00%
F1 Score: 100.00

Confusion Matrix:
 [[614   0]
 [  0 386]]


## 1.2 Model Naive Bayes

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((4000,), (1000,), (4000,), (1000,))

In [31]:
from sklearn.impute import SimpleImputer

# Menggantikan nilai np.nan dengan string kosong ''
X_train_cleaned = np.where(pd.isnull(X_train), '', X_train)

# Menerapkan TfidfVectorizer pada data yang telah dikosongkan
vect = TfidfVectorizer(max_features=1000, binary=True)
X_train_vect = vect.fit_transform(X_train_cleaned)

sm = SMOTE()
X_train_res, y_train_res = sm.fit_resample(X_train_vect, y_train)

unique, counts = np.unique(y_train_res, return_counts=True)
print(list(zip(unique, counts)))



[('Negatif', 2460), ('Positif', 2460)]


In [32]:
#Melihat kinerja model
nb = MultinomialNB()
nb.fit(X_train_res, y_train_res)
nb.score(X_train_res, y_train_res)

0.7932926829268293

In [33]:
X_test_vect = vect.transform(X_test)
y_pred = nb.predict(X_test_vect)

print("Accuracy: {:.2f}%".format(accuracy_score(y_test, y_pred) * 100))
print("F1 Score: {:.2f}".format(f1_score(y_test, y_pred, average='weighted') * 100))
print("\nCOnfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 71.60%
F1 Score: 71.88

COnfusion Matrix:
 [[445 169]
 [115 271]]


## 2. Membandingkan Akurasi score dari Analisis sentimen menggunakan model SVM pada Dataset COD dan PUBG 

In [34]:
# Menentukan ambang batas untuk mengkategorikan sentimen
threshold_positif = 4
threshold_negatif = 3

# Menerapkan analisis sentimen berdasarkan skor
df_COD['Sentimen'] = df_COD['Rating'].apply(lambda x: 'Positif' if x >= threshold_positif else 'Negatif')

# Menyimpan hasil analisis sentimen ke dalam data frame
df_COD = df_COD[['Komentar','Sentimen']]

# Menerapkan analisis sentimen berdasarkan skor
df_PUBG['Sentimen'] = df_PUBG['Rating'].apply(lambda x: 'Positif' if x >= threshold_positif else 'Negatif')

# Menyimpan hasil analisis sentimen ke dalam data frame
df_PUBG = df_PUBG[['Komentar','Sentimen']]

In [35]:
df_COD

Komentar Sentimen
0     terlalu sangat banyak update tidak jelas simpa...  Negatif
1     permainan salah satu game favorit saya game ke...  Positif
2     game sudah bagus sesungguh semua bagus kecuali...  Negatif
3           mencari musuh tolong yang pintar kemampuan   Negatif
4     pilih tim sesuai skill bawah saya dan lawan se...  Negatif
...                                                 ...      ...
4995  bagus ada beberapa masuk contoh damage  kaki k...  Positif
4996  good permainan tingkat  lagi senjata lebih ban...  Positif
4997  orang bodoh yang asal nilai kecil mereka tidak...  Positif
4998  untuk dari permainan garena sendiri sudah bagu...  Positif
4999  kontrol kurang nyaman dengan sensitifitas terl...  Negatif

[5000 rows x 2 columns]

In [36]:
df_PUBG

Komentar Sentimen
0     saya sering saat loading  permainan kembali lo...  Negatif
1     bagus  lama ini tapi peta livik masih harus pe...  Positif
2     mohon awasi karena saya bisa login lewat email...  Positif
3     game terlalu lama loadingnya buat tidak suka d...  Negatif
4     kirain sudah kasih ulasan permainan  lebih per...  Negatif
...                                                 ...      ...
4995  semakin lama permainan semakin kualitas hampir...  Negatif
4996  banyak lambat  sudah update grafis sudah palin...  Negatif
4997  kenapa sekarang suka dan sering keluar sendiri...  Positif
4998  pertama belum upgrade bagus sekarang sudah upg...  Negatif
4999  lemah update baru semakin sering lambat patah ...  Negatif

[5000 rows x 2 columns]

## 2.1 Model SVM dataset COD

In [37]:
from sklearn.model_selection import KFold
from sklearn.svm import SVC


X = df_COD["Komentar"]  
y = df_COD["Sentimen"]  

# Membuat objek KFold dengan k=5
kfold_COD= KFold(n_splits=5, shuffle=True, random_state=42)

# Melakukan Stratified K-Fold Cross Validation pada data
for fold, (train_index, test_index) in enumerate(kfold_COD.split(X, y)):
    
    # Subset data pelatihan dan data pengujian
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

In [38]:
# Inisialisasi vectorizer dan mengubah data latih ke dalam representasi vektor
vectorizer_COD = TfidfVectorizer(max_features=1000, binary=True)
X_vect = vectorizer_COD.fit_transform(X_train)

# Melakukan oversampling menggunakan SMOTE
sm = SMOTE()
X_train_res, y_train_res = sm.fit_resample(X_vect, y_train)

# Membuat model SVM
model_SVM = SVC(kernel='linear')

# Melakukan cross validation
scores = cross_val_score(model_SVM, X_train_res, y_train_res, cv=kfold_COD)

# Menampilkan hasil kinerja model pada setiap fold
for fold, score in enumerate(scores):
    print("Fold", fold+1, "Accuracy:", score*100,"%")

Fold 1 Accuracy: 74.88151658767772 %
Fold 2 Accuracy: 77.46144721233689 %
Fold 3 Accuracy: 74.4958481613286 %
Fold 4 Accuracy: 72.00474495848161 %
Fold 5 Accuracy: 74.85172004744959 %


In [39]:
# Melatih model dengan data latih yang telah di-resampling
model_SVM.fit(X_train_res, y_train_res)

# Menghitung akurasi dan prediksi pada data uji
X_test_vect = vectorizer_COD.transform(X_test)
y_pred = model_SVM.predict(X_test_vect)

# Menampilkan hasil evaluasi model
print("Accuracy: {:.2f}%".format(accuracy_score(y_test, y_pred) * 100))
print("F1 Score: {:.2f}".format(f1_score(y_test, y_pred, average='weighted') * 100))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 74.60%
F1 Score: 74.65

Confusion Matrix:
 [[414 140]
 [114 332]]


## 2.2 Model SVM dataset PUBG

In [40]:
from sklearn.model_selection import KFold

X = df_PUBG["Komentar"]  
y = df_PUBG["Sentimen"]  

# Membuat objek KFold dengan k=5
kfold_PUBG = KFold(n_splits=5, shuffle=True, random_state=42)

# Melakukan Stratified K-Fold Cross Validation pada data
for fold, (train_index, test_index) in enumerate(kfold_PUBG.split(X, y)):
    
    # Subset data pelatihan dan data pengujian
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

In [41]:
# Inisialisasi vectorizer dan mengubah data latih ke dalam representasi vektor
vectorizer_PUBG = TfidfVectorizer(max_features=1000, binary=True)
X_vect = vectorizer_PUBG.fit_transform(X_train)

# Melakukan oversampling menggunakan SMOTE
sm = SMOTE()
X_train_res, y_train_res = sm.fit_resample(X_vect, y_train)

# Membuat model SVM
model_SVM = SVC(kernel='linear')

# Melakukan cross validation
scores = cross_val_score(model_SVM, X_train_res, y_train_res, cv=kfold_PUBG)

# Menampilkan hasil kinerja model pada setiap fold
for fold, score in enumerate(scores):
    print("Fold", fold+1, "Accuracy:", score*100,"%")


Fold 1 Accuracy: 76.8141592920354 %
Fold 2 Accuracy: 76.10619469026548 %
Fold 3 Accuracy: 74.60176991150442 %
Fold 4 Accuracy: 76.99115044247787 %
Fold 5 Accuracy: 76.90265486725664 %


In [42]:
# Melatih model dengan data latih yang telah di-resampling
model_SVM.fit(X_train_res, y_train_res)

# Menghitung akurasi dan prediksi pada data uji
X_test_vect = vectorizer_PUBG.transform(X_test)
y_pred = model_SVM.predict(X_test_vect)

# Menampilkan hasil evaluasi model
print("Accuracy: {:.2f}%".format(accuracy_score(y_test, y_pred) * 100))
print("F1 Score: {:.2f}".format(f1_score(y_test, y_pred, average='weighted') * 100))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 72.00%
F1 Score: 73.08

Confusion Matrix:
 [[545 185]
 [ 95 175]]


Kesimpulan:
Dengan menganalisis sentimen dari ulasan para pemain, proyek ini bertujuan untuk memperoleh wawasan tentang persepsi secara keseluruhan mengenai game PUBG, FF, dan COD di kalangan pemain. Hal ini dapat membantu pengembang dan penerbit game dalam memahami kelebihan, kelemahan, dan area yang perlu diperbaiki dari game-game tersebut berdasarkan umpan balik dari para pemain.